# Generated by Django 4.1.5 on 2024-02-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animal_animal_type_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='decsription',
            new_name='description',
        ),
    ]
