name: Checks

on: [push]

jobs:
    test:
        name: Tests
        runs-on: ubuntu-20-04
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username:${{ secrets.DOCKER_HUB_USER }}
                password:${{ secrets.DOCKER_HUB_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test
              run: docker-compose run -rm app sh -C "python manage.py test"






